### ISSUE TITLE
san 组件方法里的 this 指向不对

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#10]
开发中发现， san-ssr 对源码中的 `this.data.get` 在不同场景下转换的结果不同：

- computed 方法中： `$this->data->get`
- 普通方法中： `$this->data["get"]`

导致运行时， 普通方法中报错 `Fatal error: Object does not implement ArrayAccess`

**Comment by harttle** [comment]
优先从 san 核心的类型定义上来解决，其次可以在 ssr 时魔改类型。
