### ISSUE TITLE
'interface' or 'abstract class'

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#11]
RT, 定义一个对象类型时是用 `interface` 还是 `abstract class`?

另外， 若使用 `abstract class` ,  则类型里字段名不能被引号包起来， 否则编译产出错误：

```typescript
// 输入
abstract class TmpX {
    'data-x': string
}

abstract class TmpX1 {
    'datax': string
}

abstract class TmpX2 {
    datax: string
}
```

```php
// 输出
    abstract class TmpX {
        public ;
    }
    abstract class TmpX1 {
        public ;
    }
    abstract class TmpX2 {
        public $datax;
    }
```

这样就会导致 `data-x` 这样的属性名没法被支持， 求解。

**Comment by harttle** [comment]
分两个问题来看：

1. interface 不可用的问题。定义类型的标准方法就是interface，这个需求需要支持。
2. interface 中不能有不符合标识符命名规则的属性名的问题（是否存在？只是class才有问题？），TypeScript 是支持的，PHP 对象也支持。因此可以解决。

**Comment by harttle** [comment]
新增了这个case： https://github.com/searchfe/san-ssr/blob/master/test/cases/method/component.ts
