### ISSUE TITLE
$template 属性赋值后置

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#16]
$template 的赋值有时候会是变量或表达式， 目前编译产出如下： 

```php
class DemoComponent extends Component {
    public static $filters;
    public static $computed;

    // $templateHTML 是个变量
    public static $template = $templateHTML;
}
```

发现运行时报错： `Fatal error: syntax error, unexpected T_VARIABLE`， 查了下[文档](https://www.php.net/manual/zh/language.oop5.properties.php)， 说是：

> 属性中的变量可以初始化，但是初始化的值必须是常数，这里的常数是指 PHP 脚本在编译阶段时就可以得到其值，而不依赖于运行时的信息才能求值。

改成下面这样就好使了：

```php
class DemoComponent extends Component {
    public static $filters;
    public static $computed;
    public static $template;
}
DemoComponent::$template = $templateHTML;
```

**Comment by harttle** [comment]
已经修复。参考这个 case：

https://github.com/searchfe/san-ssr/blob/b112ed53929400e252aae088ce8a696833e0cd01/test/cases/property-initializer/component.ts#L5-L12
