### ISSUE TITLE
san-ssr 的 PHP 版本建议添加配置项来确定是否需要输出反解注释

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#21]
建议根据 [render 函数的 noOutputData 参数](https://github.com/searchfe/san-ssr/issues/14)来确定， 配置不输出数据的话， [反解](https://baidu.github.io/san/tutorial/reverse/)相关的注释也都不输出:

- 序列化的数据
- 复合插值文本标记

**Comment by PengXing** [comment]
补充一个例子

```html
<script type="text/javascript">
  page.comm1 = page.comm1 || {};
  page.comm1.isShowInapp = {{queryInfo.showInapp ? 1 : 0}};
</script>
```

![image](https://user-images.githubusercontent.com/527244/68668723-cf993380-0583-11ea-992c-410507f92250.png)
