### ISSUE TITLE
inited 生命周期在 ssr 编译期不应该执行

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#41]
inited 生命周期在 ssr 编译期不应该执行， 因为里面有很多数据处理逻辑， 都是运行时的， 在编译期处理很容易挂掉。

同时建议必须有 initData， 没有的话让编译直接报错 @harttle 。

created, attached  生命周期之前试过， 在 ssr 里会被忽略掉。

**Comment by harttle** [comment]
我发现 san-ssr-target-php 里已经把 inited 从编译时移到了运行时。这个 Issue： https://github.com/searchfe/san-ssr-target-php/issues/3 。理由是，

> 1. 编译期的 inited 主要用途是数据处理（因为它不能访问 DOM/BOM），且它和 initData() 的输入一样，作用是冗余的。
> 2. inited 声明周期的语义是实例初始化完成，这是一个运行时概念。这样里面做一些比如统计组件初始化时序、运行时性能等操作才能正确执行。

且目前 ssr 的 test case 里没有 inited 相关测试，可以算不 break 只是一些工作从编译时移到运行时。

@PengXing @errorrik 看下靠谱不，OK 的话 san-ssr 也做这个改动。

**Comment by PengXing** [comment]
我觉得靠谱，如果 san ssr 在编译期就要运行所有的 JS 逻辑，那么也就是在编译期就要传递全部的数据，有点本末倒置了
