### ISSUE TITLE
san-ssr 对空值属性的渲染和 san 原生渲染有 diff

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#5]
RT, 使用中发现如下 diff：

```html
<!-- san template -->
<div a1="{{''}}" a2="{{null}}" a3="{{false}}" a4="{{undefined}}" a5="{{0}}" a6="{{[]}}" a7="{{true}}" a8="{{}}" a9>属性绑定元素载体</div>

<!-- san 渲染出的 html -->
<div a8="{{}}" a1="" a2="" a3="false" a4="" a5="0" a6="" a7="true" a9="">属性绑定元素载体</div>


<!-- san-ssr 渲染出的 html -->
<div a7="true">属性绑定元素载体</div>
```

可参考这个在线 Demo： https://codesandbox.io/embed/san-demo-dvnpb ， @harttle 看看是否需要对齐？

---

另外， 其实我真正的需求是希望能有一种方法能渲染出以下两种结果：

- 跟据条件判断确定属性是否可以不渲染

  > san 的[属性整体绑定](https://baidu.github.io/san/tutorial/template/#%E5%B1%9E%E6%80%A7%E6%95%B4%E4%BD%93%E7%BB%91%E5%AE%9A) 已支持， 单个属性绑定暂不支持

- 跟据条件判断确定属性要么不渲染， 要么只渲染属性名（相当于 HTML 里的布尔属性)

  > san 暂时不支持

已经给 san 提 [issue](https://github.com/baidu/san/issues/442) 了，  @harttle 看看 san-ssr 是否可以先自行实现这两个功能。

**Comment by harttle** [comment]
san-ssr 先对齐 san 客户端渲染结果，后续两个问题从 san 核心仓库来跟进。
